<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema" name="omnibase">

  <!-- Materials -->
  <material name="darkgrey">
    <color rgba="0.1 0.1 0.1 1.0" />
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0" />
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0" />
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- Constants from base_ws mecanumbot -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />

  <!-- Base dimensions - larger platform for drone landing -->
  <xacro:property name="base_size_x" value="1.0" />
  <xacro:property name="base_size_y" value="0.8" />
  <xacro:property name="base_size_z" value="0.05" />
  <xacro:property name="base_mass" value="10.0" />

  <!-- Wheel parameters - scaled from base_ws (0.03 -> 0.06 for larger base) -->
  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="wheel_offset_x" value="0.38"/>
  <xacro:property name="wheel_offset_y" value="0.44"/>
  <xacro:property name="wheel_offset_z" value="-0.05"/>
  <xacro:property name="wheel_mass" value="0.500"/>
  <xacro:property name="mesh_scale" value="1.2"/>

  <!-- Inertia macros from base_ws -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
             iyy="${m*(x*x+z*z)/12}" iyz="0"
             izz="${m*(x*x+z*z)/12}"
    />
  </xacro:macro>
  <xacro:macro name="cylinder_inertia" params="m r w">
    <inertia ixx="${m*(3*r*r+w*w)/12}" ixy="0" ixz="0"
             iyy="${m*(3*r*r+w*w)/12}" iyz="0"
             izz="${m*r*r/2}"
    />
  </xacro:macro>

  <!-- Base Footprint -->
  <link name="base_footprint" />

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>   
        <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="${base_mass}"/>
      <xacro:box_inertia m="${base_mass}" x="${base_size_x}" y="${base_size_y}" z="${base_size_z}"/>
    </inertial>
  </link>

  <!-- Front Left Wheel -->
  <joint name="fl_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="fl_wheel_link"/>
    <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${-M_PI/2}" />
    <axis xyz="1 0 0" rpy="0 0 0"/>
  </joint>
  <link name="fl_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://omnibase_description/meshes/fl_wheel_link.STL" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}" />
      </geometry>
      <material name="darkgrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
    </inertial>
  </link>

  <!-- Front Right Wheel -->
  <joint name="fr_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="fr_wheel_link"/>
    <origin xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${M_PI/2}" />
    <axis xyz="-1 0 0" rpy="0 0 0"/>
  </joint>
  <link name="fr_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://omnibase_description/meshes/fr_wheel_link.STL" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}" />
      </geometry>
      <material name="darkgrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
    </inertial>
  </link>

  <!-- Rear Left Wheel -->
  <joint name="rl_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rl_wheel_link"/>
    <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${-M_PI/2}" />
    <axis xyz="1 0 0" rpy="0 0 0"/>
  </joint>
  <link name="rl_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://omnibase_description/meshes/rl_wheel_link.STL" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}" />
      </geometry>
      <material name="darkgrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
    </inertial>
  </link>

  <!-- Rear Right Wheel -->
  <joint name="rr_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rr_wheel_link"/>
    <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${M_PI/2}" />
    <axis xyz="-1 0 0" rpy="0 0 0"/>
  </joint>
  <link name="rr_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://omnibase_description/meshes/rr_wheel_link.STL" scale="${mesh_scale} ${mesh_scale} ${mesh_scale}" />
      </geometry>
      <material name="darkgrey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
    </inertial>
  </link>

  <!-- Camera Mount (retained from original omnibase) -->
  <link name="camera_mount">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_mount"/>
    <origin xyz="0 0 ${base_size_z/2 + 0.025}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0"
               iyy="0.00001" iyz="0.0"
               izz="0.00001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="camera_mount"/>
    <child link="camera_link"/>
    <origin xyz="0 0 0.035" rpy="0 0 0"/>
  </joint>

  <!-- Camera Optical Frame (pointing up) -->
  <link name="camera_optical_link"/>
  
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_link"/>
    <!-- Rotate to point upward: -90 deg around X, then -90 deg around Z -->
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
  </joint>

  <!-- Gazebo Harmonic Material Colors -->
  <gazebo reference="base_link">
    <visual>
      <material>
        <ambient>0.0 0.0 0.8 1</ambient>
        <diffuse>0.0 0.0 0.8 1</diffuse>
        <specular>0.1 0.1 0.1 1</specular>
      </material>
    </visual>
  </gazebo>
  <!-- FL wheel: rollers at +45 degrees, fdir1 oriented accordingly -->
  <gazebo reference="fl_wheel_link">
    <visual>
      <material>
        <ambient>0.1 0.1 0.1 1</ambient>
        <diffuse>0.1 0.1 0.1 1</diffuse>
        <specular>0.1 0.1 0.1 1</specular>
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>0.0</mu2>
            <fdir1 gz:expressed_in="base_link">0.707 0.707 0</fdir1>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
  </gazebo>
  <!-- FR wheel: rollers at -45 degrees -->
  <gazebo reference="fr_wheel_link">
    <visual>
      <material>
        <ambient>0.1 0.1 0.1 1</ambient>
        <diffuse>0.1 0.1 0.1 1</diffuse>
        <specular>0.1 0.1 0.1 1</specular>
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>0.0</mu2>
            <fdir1 gz:expressed_in="base_link">0.707 -0.707 0</fdir1>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
  </gazebo>
  <!-- RL wheel: rollers at -45 degrees -->
  <gazebo reference="rl_wheel_link">
    <visual>
      <material>
        <ambient>0.1 0.1 0.1 1</ambient>
        <diffuse>0.1 0.1 0.1 1</diffuse>
        <specular>0.1 0.1 0.1 1</specular>
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>0.0</mu2>
            <fdir1 gz:expressed_in="base_link">0.707 -0.707 0</fdir1>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
  </gazebo>
  <!-- RR wheel: rollers at +45 degrees -->
  <gazebo reference="rr_wheel_link">
    <visual>
      <material>
        <ambient>0.1 0.1 0.1 1</ambient>
        <diffuse>0.1 0.1 0.1 1</diffuse>
        <specular>0.1 0.1 0.1 1</specular>
      </material>
    </visual>
    <collision>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>0.0</mu2>
            <fdir1 gz:expressed_in="base_link">0.707 0.707 0</fdir1>
            <slip1>0.0</slip1>
            <slip2>0.0</slip2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
  </gazebo>

  <!-- Upward Camera Sensor for Gazebo -->
  <gazebo reference="camera_link">
    <sensor name="upward_camera" type="camera">
      <!-- Rotate camera to point upward: pitch -90 degrees (around Y axis) -->
      <pose>0 0 0 0 -1.5708 0</pose>
      <update_rate>30.0</update_rate>
      <camera name="upward_camera">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <topic>camera</topic>
    </sensor>
  </gazebo>

  <!-- Odometry Publisher -->
  <gazebo>
    <plugin filename="gz-sim-odometry-publisher-system" name="gz::sim::systems::OdometryPublisher">
      <odom_frame>odom</odom_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <odom_topic>/model/omnibase/odometry</odom_topic>
      <odom_publish_frequency>50</odom_publish_frequency>
    </plugin>
  </gazebo>

  <!-- Velocity Control - enables direct cmd_vel control of base -->
  <gazebo>
    <plugin filename="gz-sim-velocity-control-system" name="gz::sim::systems::VelocityControl">
      <topic>/model/omnibase/cmd_vel</topic>
      <initial_linear>0 0 0</initial_linear>
      <initial_angular>0 0 0</initial_angular>
    </plugin>
  </gazebo>

  <!-- ros2_control for Gazebo Harmonic simulation -->
  <ros2_control name="omnibase_sim" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>
    <joint name="fl_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="fr_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rl_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
    <joint name="rr_wheel_joint">
      <command_interface name="velocity" />
      <state_interface name="position" />
      <state_interface name="velocity" />
    </joint>
  </ros2_control>

  <!-- Gazebo ros2_control plugin -->
  <gazebo>
    <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>$(find omnibase_control)/config/mecanum_controllers.yaml</parameters>
      <ros>
        <remapping>/controller_manager/robot_description:=/robot_description</remapping>
      </ros>
    </plugin>
  </gazebo>

</robot>
